### ISSUE TITLE
Del key does not work in termux/DroidVim 

### ISSUE THREAD

**Issue by miguehm** [8VIM/8VIM#405]
**Describe the bug**
Del key does not work inside these apps. 

**To Reproduce**
1. Go to 'Termux/DroidVim'
2. Write some text in (insert mode in DroidVim). 
3. Press Del key. 
4. Text does not delete. 

**Expected behavior**
Text get deleted. 

**Smartphone**
 - Device: Redmi Note 7
 - OS: Android 13 Pixel Experience
 - Termux 0.118.0 / DroidVim 2.14.13

**Comment by MaethorNaur** [comment]
Hi, this has been resolved on #394

**Comment by miguehm** [comment]
Ohh thanks!
I had installed before the 0.15.0 rc 17 latest pre release version and the keyboard closed unexpectedly when I used the backspace key in termux/droidvim

This 0.15.0 rc 13 version works fine for me

**Comment by MaethorNaur** [comment]
I'll have a look at then 👍🏾

**Comment by MaethorNaur** [comment]
> Ohh thanks! I had installed before the 0.15.0 rc 17 latest pre release version and the keyboard closed unexpectedly when I used the backspace key.
> 
> This 0.15.0 rc 13 version works fine for me

Just with those apps or in general?

**Comment by miguehm** [comment]
> > Ohh thanks! I had installed before the 0.15.0 rc 17 latest pre release version and the keyboard closed unexpectedly when I used the backspace key.
> > 
> > This 0.15.0 rc 13 version works fine for me
> 
> Just with those apps or in general?

Yes, just those apps, in other apps I haven't had any problems

**Comment by MaethorNaur** [comment]
@miguehm Should be fixed on https://github.com/8VIM/8VIM/releases/tag/v0.15.0-rc.19.
Let me know if that's working

**Comment by miguehm** [comment]
> @miguehm Should be fixed on https://github.com/8VIM/8VIM/releases/tag/v0.15.0-rc.19.
> Let me know if that's working

I just installed it and the backspace key still not working properly  : /

**Comment by MaethorNaur** [comment]
My bad. I've changed a method called and didn't reject it. A new RC will be ready in a few min

**Comment by MaethorNaur** [comment]
@miguehm https://github.com/8VIM/8VIM/releases/tag/v0.15.0-rc.20

**Comment by miguehm** [comment]
> @miguehm https://github.com/8VIM/8VIM/releases/tag/v0.15.0-rc.20

Now it works correctly!!
