### ISSUE TITLE
Ability to add hex or rgb colors as background and foreground.

### ISSUE THREAD

**Issue by SleepyScribe** [8VIM/8VIM#467]
I like to theme everything to the teeth and lately I've been creating my own version of the Dracula theme that uses unsaturated and dimmer colors for people like me that have moderate to severe astigmatism and light eyes. I've added this theme to everything to extensively test it on my own eyes first.

I would love to be able set this theme on 8VIM. Would it be possible to have a hex color input or similar at the bottom of the color picker so that we could input our own colors?

**Comment by MaethorNaur** [comment]
@SleepyScribe does the change available from the APK from #480 works for you?

**Comment by SleepyScribe** [comment]
> @SleepyScribe does the change available from the APK from #480 works for you?

This 100% works great in terms of the color wheel setting the color and I'm excited for full release. Thank you so much! The keyboard did crash once when deleting the hex color characters, but my Z Fold 3 seems to not like the beta builds.

For example, I seem to have trouble getting the debug/beta symbol keyboard to register inputs, and I can't get back to the regular keyboard screen through the button, I have to close the keyboard and reopen it.

(Sorry, I accidentally closed the issue by mistake.)

**Comment by MaethorNaur** [comment]
@SleepyScribe Yes it seems to crash randomly when the hex code is invalid. Not sure if it's only in "debug" mode (like the generated APK in PRs).
This issue is a bit weird as incorrect hex code should have been handled 🤷🏾

**Comment by SleepyScribe** [comment]
@MaethorNaur Yeah, I'm not too sure, I don't have anything that could troubleshoot or debug (I'm just a super beginner webnoob, the most I know is CSS/Tailwind right now).

I did manage to get the colors I wanted on the second try, so it feels like it's handling the error some of the time. The RC version off the app is unfortunately still unusable for me due to the symbol keyboard, but I'm confident things will be smooth on full release and will be patient until then.

**Comment by MaethorNaur** [comment]
@SleepyScribe What's the issue with the `symbol keyboard`?
Also RCs are there to be tested and report bugs before releasing :) but they can be unstable :(

**Comment by SleepyScribe** [comment]
@MaethorNaur The input for the symbols on both Fold screens tend to freeze up, making it so that I have to push the symbol several times to get it to register. The symbol to go back to the main keyboard won't work altogether, forcing me to have to back out of the keyboard and bring it back up.

The stable version works great without that issue at all, so I've just been using that and figure that the issue should work out in a later version. I'm going to test the beta on my gf's Pixel 8 Pro and see if the issue persists. I'll get back to you on that.

**Comment by MaethorNaur** [comment]
@SleepyScribe Does it freeze it should be displayed or when pressing a symbol?
Could you share a video when that's happening?

**Comment by SleepyScribe** [comment]
@MaethorNaur It's hard to capture on video, but I'll try to explain it better. Say I constantly tap the number 1. 70% of those taps won't register. It doesn't matter how fast or slow I tap it, nothing happens most of the time. It doesn't freeze per say, just feels like it does because it seems laggy.

**Comment by MaethorNaur** [comment]
@SleepyScribe Right, thanks I am aware of that issue 👍🏾 I'll have a look when I have some times

**Comment by SleepyScribe** [comment]
@MaethorNaur No biggie, I'm super happy with the color wheel and excited for release, but I'm also very content with the stable version.

Let me know if you want testing from a Z Fold user, I'll grab latest beta builds from time to time to try out, but if you have a specific build you want tested, let me know!

**Comment by MaethorNaur** [comment]
> @MaethorNaur It's hard to capture on video, but I'll try to explain it better. Say I constantly tap the number 1. 70% of those taps won't register. It doesn't matter how fast or slow I tap it, nothing happens most of the time. It doesn't freeze per say, just feels like it does because it seems laggy.

Should be fixed with #482

**Comment by SleepyScribe** [comment]
@MaethorNaur Problem still persists on both screens. If it helps, it seems like I can press every key once and then not again, which is different from before. Switching back to keyboard and extended symbols still doesn't seem to work so much.

**Comment by MaethorNaur** [comment]
@SleepyScribe Which version of android are you running on?

**Comment by SleepyScribe** [comment]
@MaethorNaur Android version 14 running OneUI 6.0.

**Comment by MaethorNaur** [comment]
@SleepyScribe Does #483 fix the issue?

**Comment by SleepyScribe** [comment]
@MaethorNaur Still the same. Once everything is pushed once, it doesn't seem to want to work again until I uninstall and reinstall the keyboard. Lemme try clearing cache and data and try uninstalling the stable version, I'll edit with an update.

Edit: I've tried toggling everything on and off, still the same. If I delete the data, then I can push every key once again and then they go back to not working/working 10% of the time.

**Comment by SleepyScribe** [comment]
@MaethorNaur I just want to confirm for you that it is indeed Samsung (at least the Z Fold 3) that causes the symbol board to malfunction.

I switched to the Pixel 7 Pro and the RC board works great. I thought this information could possibly be useful to you.

**Comment by MaethorNaur** [comment]
Interesting I'll look into it if there're bugs on the functions used and z fold

**Comment by SleepyScribe** [comment]
@MaethorNaur If it helps at all, the stable version works fine on the Z Fold. There's something between the two versions that causes it, if that helps at all.

**Comment by MaethorNaur** [comment]
@SleepyScribe I've created an issue for that (#485) so I can close this one
